### ISSUE TITLE
Can a protocol path be any sort of address with a 'multiaddr-like' format?

### ISSUE THREAD

**Issue by ghost** [multiformats/multistream#3]
Hi,

I'm currently working on a Haskell version of multistream / multistream-muxer, and I wasn't sure about what sort of protocol paths are accepted here.

So, is it correct that the protocol paths mentioned in the readme corresponds to some arbitrary address that doesn't have to be a multiaddr or a multicodec, but has the same format? I'm also unsure as to what the correct terminology would be for these protocol paths (multistream?).

For example,
"/spongebob/1.0.0" would be a valid protocol path, even though "spongebob" is neither a codec listed in the multicodec table nor an address in the multiaddr table.

This behaviour would be consistent with the tests implemented in the go-multistream library here:
https://github.com/multiformats/go-multistream/blob/master/multistream_test.go

However, I noticed this issue raised in the multiformats/multistream-select repo:
https://github.com/multiformats/multistream-select/issues/8 that says,

> Update Docs + API after the matchingFunc discussion. We discussed:
> - multistream takes in a tuple: (multicodec-header, handlerFunc, matchingFunc)
> - handlerFunc is called with the header
> - matchingFunc decides whether a header matches.
> - default matchingFunc is equivalence (tests the given header matches the original one)

Since multicodecHeader is listed as a type there, this seems to suggest that the protocol path as mentioned in the readme is some sort of multicodec path?

For the most part, I would like to avoid identifying objects such as handlers with strings where possible, and instead try to make use of Haskell's type system to do the matching between a handler and its corresponding protocol by parsing the incoming byte stream to some type that represents the fact that it is a valid protocol + what the protocol path is. This may make sense depending on the constraints on exactly what constitutes a protocol path.

Any help related to this or implementing LibP2P in Haskell would be greatly appreciated.

Thanks

**Comment by diasdavid** [comment]
Hi @plintX! That is super cool, I want a Haskell implementation for a while. Mind if I take partake in the development? I can provide more of guidance while I get acquaintance with Haskell.

Answering your question: multicodec has its binary packed and its long version, in multistream we only use the long version because otherwise it would require us to handshake a table on each conn, something we might do, but not for now at least. So yes, all of this multistream protocols are valid multicodecs, they just don't have a binary packed version.

**Comment by plintX** [comment]
Of course, that would be great.

I'll upload my WIP to a github repo sometime this week. 

Intending to represent byte streams using the io-streams library in Haskell, along with the attoparsec library to do parsing on the stream. That seems to be consistent with the libraries that @LukeHoersten used in his implementation of https://github.com/multiformats/haskell-multihash.

RE: multicodec
So in other words, does that mean
"/putAnyNameHere/1.0.0" literally constitutes a valid multicodec?

**Comment by LukeHoersten** [comment]
@plintX sounds like a great plan! 👍 `io-streams` is simple and high-performant because it defaults to being in the IO monad. Attoparsec and io-streams were designed to integrate well together.

**Comment by plintX** [comment]
Hey @diasdavid, I've put up some of my work at:
https://github.com/MatrixAI/haskell-multistream
, it's not complete at all but there if you want to work on or have a look at

**Comment by diasdavid** [comment]
> So in other words, does that mean "/putAnyNameHere/1.0.0" literally constitutes a valid multicodec?

Indeed it is :) 

> https://github.com/MatrixAI/haskell-multistream

Rad, will take a look at it! Any questions right now?

**Comment by vmx** [comment]
I dare to close this issue as this spec is deprecated.
