### ISSUE TITLE
The link to `multicodec-packed.md` is broken.

### ISSUE THREAD

**Issue by abourget** [multiformats/multistream#4]

**Comment by llopv** [comment]
There was a [naming change](https://github.com/multiformats/multicodec/pull/16#issuecomment-249497577) some time ago, and the multicodec repo [got splitted](https://github.com/multiformats/multicodec/commit/b923744653abb9756b963d2cea086e2dc9ed89a2).

I suppose it has no sense talking about "codecs" in this repo anymore, and replace them by "streams". The FAQ _Why "codec" and not "encoder" and "decoder"?_ has no sense anymore, and the link multicodec-packaged should be changed to just multicodec and point to the multicodec repo.

@diasdavid can you check it? I was not in the "codec" <-> "stream" discussion.

**Comment by vmx** [comment]
I'm closing this issue as this spec is deprecated and the README is currently kept for historic purpose (with all its bugs).
