### ISSUE TITLE
Is multistream an actual thing?

### ISSUE THREAD

**Issue by vmx** [multiformats/multistream#9]
After reading through the README it seems to me that multistream isn't something that is actually used or implemented. The Go and JS implementations point to multistream-select. Multistream reads like a left-over from earlier multiformat attempts.

Please enlighten me on what this is for and whether it is used or not.

**Comment by Stebalien** [comment]
See the history in: https://github.com/multiformats/multicodec/issues/133#issuecomment-495821973 (to the best of my knowledge).

**Comment by vmx** [comment]
Given that history, it would mean that multistream isn't used (multistream-select is something different) and that it even shouldn't be used as we don't use strings for multicodecs anymore.

This would mean that we could just delete this spec?
